import "@/styles/global.css";
import GlassPane from "@/components/GlassPane";
import SideBar from "@/components/SideBar";

export const metadata = {
  title: "Signin",
  description: "Generated by create next app",
};

export default function DashboardRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen w-screen candy-mesh p-6">
        <GlassPane className="w-full h-full flex items-center justify-center">
          <SideBar />
          {children}
        </GlassPane>
      </body>
    </html>
  );
}
